### PR TITLE
feature: Add user routes

### PR DESCRIPTION
**Pull request by ShrudhiPriya**
I was working on the databases and the endpoints and ran into a wall. Currently I am trying to connect our endpoints to our DBEaver Database. To confirm the below: 
1. Do we still need the init_db.sql file as it is outdated?
2. Replace our database.js file code : let sql = fs.readFileSync(__dirname + "/init_db.sql").toString();.
to this code instead then: let sql = fs.readFileSync(__dirname + "/" + file).toString();.

### CODE REVIEW

**Review by sssoja — COMMENTED** [review]
Hi Shrudhi, have a look again at where you're trying to merge this branch. Currently you're trying to merge this feature branch to `main`. Can you update this pull request so that it's pointing to `staging`?

**Comment by ShrudhiPriya** [comment]
Apologies. I have changed it staging.

**Review by sssoja — COMMENTED** [review]
Check again this line `const recipes = await db("SELECT * FROM target");` in your `milestones.js` what would be an appropriate name for this variable?

**Review by sssoja — CHANGES_REQUESTED** [review]
I would also rename the `target.js` to `targets.js` and the query should also read     `await db("SELECT * FROM **targets**");`

**Comment by ShrudhiPriya** [comment]
I have amended the files for remote database connection. Please help check why this cannot be merged. 
Endpoints creation to be confirmed.

**Comment by sssoja** [comment]
> I have amended the files for remote database connection. Please help check why this cannot be merged. Endpoints creation to be confirmed.

Hi @ShrudhiPriya, as there has since been changes to `staging` you will need to merge these changes into your feature branch. Once these merge conflicts have been resolved, you will be able to proceed.

**Pull request closed without merging**
